// frontend/src/components/PageLayout.tsx
import type { PropsWithChildren, ReactNode } from "react";

type PageLayoutProps = PropsWithChildren<{
  title: string;
  subtitle?: string;
  actions?: ReactNode;
  narrow?: boolean;
}>;

export default function PageLayout({
  title,
  subtitle,
  actions,
  narrow = false,
  children,
}: PageLayoutProps) {
  return (
    <main className="page-shell">
      <section className={`card ${narrow ? "card--narrow" : ""}`}>
        <header className="page-header">
          <div>
            <h1>{title}</h1>
            {subtitle ? <p>{subtitle}</p> : null}
          </div>
          {actions ? <div className="page-header__actions">{actions}</div> : null}
        </header>
        {children}
      </section>
    </main>
  );
}

// frontend/src/components/PageLayout.vue
<script setup lang="ts">
defineProps<{
  title: string;
  subtitle?: string;
  narrow?: boolean;
}>();
</script>

<template>
  <main class="page-shell">
    <section :class="['card', { 'card--narrow': narrow }]">
      <header class="page-header">
        <div>
          <h1>{{ title }}</h1>
          <p v-if="subtitle">{{ subtitle }}</p>
        </div>
        <div v-if="$slots.actions" class="page-header__actions">
          <slot name="actions" />
        </div>
      </header>
      <slot />
    </section>
  </main>
</template>
