// frontend/src/components/PostVoteControls.tsx
import React, { useState } from "react";
import { useAuth } from "../context/AuthContext";
import { forumApi } from "../services/api/forumApi";
import type { Post } from "../types";

type PostVoteControlsProps = {
  post: Post;
  onPostChange: (post: Post) => void;
  compact?: boolean;
};

const PostVoteControls: React.FC<PostVoteControlsProps> = ({
  post,
  onPostChange,
  compact = false,
}) => {
  const { isAuthenticated } = useAuth();
  const [pending, setPending] = useState<null | -1 | 1 | 0>(null);
  const [error, setError] = useState<string | null>(null);

  const handleVoteClick =
    (value: -1 | 1) => async (event: React.MouseEvent<HTMLButtonElement>) => {
      event.stopPropagation();

      if (!isAuthenticated) {
        return;
      }

      try {
        setError(null);
        setPending(value);

        const updatedPost =
          post.currentUserVote === value
            ? await forumApi.removePostVote(post.id)
            : await forumApi.voteOnPost(post.id, { value });

        onPostChange(updatedPost);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to save vote.");
      } finally {
        setPending(null);
      }
    };

  return (
    <div className={`vote-controls${compact ? " vote-controls--compact" : ""}`}>
      <div className="vote-controls__row">
        <button
          type="button"
          className={`vote-button${post.currentUserVote === 1 ? " vote-button--active" : ""}`}
          onClick={handleVoteClick(1)}
          disabled={!isAuthenticated || pending !== null}
          aria-label="Upvote post"
        >
          +
        </button>
        <span className="vote-score" aria-label="Vote score">
          {post.voteScore}
        </span>
        <button
          type="button"
          className={`vote-button${post.currentUserVote === -1 ? " vote-button--active vote-button--down" : " vote-button--down"}`}
          onClick={handleVoteClick(-1)}
          disabled={!isAuthenticated || pending !== null}
          aria-label="Downvote post"
        >
          -
        </button>
      </div>
      {error ? <p className="vote-error">{error}</p> : null}
    </div>
  );
};

export default PostVoteControls;

// frontend/src/components/PostVoteControls.vue
<script setup lang="ts">
import { ref } from "vue";
import { useAuth } from "../composables/useAuth";
import { forumApi } from "../services/api/forumApi";
import type { Post } from "../types";

const props = withDefaults(
  defineProps<{
    post: Post;
    compact?: boolean;
  }>(),
  {
    compact: false,
  },
);

const emit = defineEmits<{
  changed: [post: Post];
}>();

const auth = useAuth();
const pending = ref<null | -1 | 1 | 0>(null);
const error = ref("");

const handleVoteClick = async (value: -1 | 1) => {
  if (!auth.isAuthenticated.value) {
    return;
  }

  try {
    error.value = "";
    pending.value = value;

    const updatedPost =
      props.post.currentUserVote === value
        ? await forumApi.removePostVote(props.post.id)
        : await forumApi.voteOnPost(props.post.id, { value });

    emit("changed", updatedPost);
  } catch (err) {
    error.value =
      err instanceof Error ? err.message : "Failed to save vote.";
  } finally {
    pending.value = null;
  }
};
</script>

<template>
  <div :class="['vote-controls', { 'vote-controls--compact': compact }]">
    <div class="vote-controls__row">
      <button
        type="button"
        :class="['vote-button', { 'vote-button--active': post.currentUserVote === 1 }]"
        :disabled="!auth.isAuthenticated.value || pending !== null"
        aria-label="Upvote post"
        @click.stop="handleVoteClick(1)"
      >
        +
      </button>
      <span class="vote-score" aria-label="Vote score">{{ post.voteScore }}</span>
      <button
        type="button"
        :class="[
          'vote-button',
          'vote-button--down',
          { 'vote-button--active': post.currentUserVote === -1 },
        ]"
        :disabled="!auth.isAuthenticated.value || pending !== null"
        aria-label="Downvote post"
        @click.stop="handleVoteClick(-1)"
      >
        -
      </button>
    </div>
    <p v-if="error" class="vote-error">{{ error }}</p>
  </div>
</template>
