// frontend/src/pages/NewPostPage.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import NoticeBanner from "../components/NoticeBanner.vue";
import PageLayout from "../components/PageLayout.vue";
import { forumApi } from "../services/api/forumApi";

const route = useRoute();
const router = useRouter();

const companyId = computed(() => Number(route.params.id));

const title = ref("");
const body = ref("");
const loading = ref(false);
const error = ref("");

const handleSubmit = async () => {
  if (!companyId.value) {
    error.value = "Company ID is missing.";
    return;
  }

  if (!title.value.trim() || !body.value.trim()) {
    error.value = "Title and body are required.";
    return;
  }

  loading.value = true;
  error.value = "";

  try {
    await forumApi.createPost(companyId.value, {
      title: title.value.trim(),
      body: body.value.trim(),
    });
    await router.push(`/companies/${companyId.value}`);
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to create post.";
  } finally {
    loading.value = false;
  }
};
</script>

<template>
  <PageLayout title="Create Post" subtitle="Add a new thread for this company.">
    <NoticeBanner v-if="error" tone="error">{{ error }}</NoticeBanner>

    <form class="form-grid" @submit.prevent="handleSubmit">
      <div class="field">
        <label for="title">Title</label>
        <input id="title" v-model="title" :disabled="loading" />
      </div>

      <div class="field">
        <label for="body">Body</label>
        <textarea id="body" v-model="body" rows="8" :disabled="loading" />
      </div>

      <div class="form-actions">
        <button class="button button--primary" type="submit" :disabled="loading">
          {{ loading ? "Creating..." : "Create Post" }}
        </button>
        <button
          class="button button--secondary"
          type="button"
          :disabled="loading"
          @click="router.push(companyId ? `/companies/${companyId}` : '/companies')"
        >
          Cancel
        </button>
      </div>
    </form>
  </PageLayout>
</template>

// frontend/src/pages/NewPostPage.tsx
import React, { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Notice from "../components/Notice";
import PageLayout from "../components/PageLayout";
import { forumApi } from "../services/api/forumApi";

const NewPostPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const companyId = Number(id);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();

    if (!companyId) {
      setError("Company ID is missing.");
      return;
    }

    if (!title.trim() || !body.trim()) {
      setError("Title and body are required.");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      await forumApi.createPost(companyId, {
        title: title.trim(),
        body: body.trim(),
      });
      navigate(`/companies/${companyId}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create post.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <PageLayout title="Create Post" subtitle="Add a new thread for this company.">
      {error ? <Notice tone="error">{error}</Notice> : null}

      <form className="form-grid" onSubmit={handleSubmit}>
        <div className="field">
          <label htmlFor="title">Title</label>
          <input
            id="title"
            value={title}
            onChange={(event) => setTitle(event.target.value)}
            disabled={loading}
          />
        </div>

        <div className="field">
          <label htmlFor="body">Body</label>
          <textarea
            id="body"
            value={body}
            onChange={(event) => setBody(event.target.value)}
            rows={8}
            disabled={loading}
          />
        </div>

        <div className="form-actions">
          <button className="button button--primary" type="submit" disabled={loading}>
            {loading ? "Creating..." : "Create Post"}
          </button>
          <button
            className="button button--secondary"
            type="button"
            onClick={() => navigate(companyId ? `/companies/${companyId}` : "/companies")}
            disabled={loading}
          >
            Cancel
          </button>
        </div>
      </form>
    </PageLayout>
  );
};

export default NewPostPage;
