// frontend/src/pages/PostDetailPage.tsx
import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Notice from "../components/Notice";
import PageLayout from "../components/PageLayout";
import PostVoteControls from "../components/PostVoteControls";
import { useAuth } from "../context/AuthContext";
import { forumApi } from "../services/api/forumApi";
import type { Comment, Post } from "../types";

const PostDetailPage: React.FC = () => {
  const { postId } = useParams<{ postId: string }>();
  const navigate = useNavigate();
  const { currentUser, isAuthenticated } = useAuth();

  const [post, setPost] = useState<Post | null>(null);
  const [comments, setComments] = useState<Comment[]>([]);
  const [newComment, setNewComment] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);

  useEffect(() => {
    const parsedId = Number(postId);
    if (!parsedId) {
      setError("Invalid post ID.");
      setLoading(false);
      return;
    }

    const fetchPost = async () => {
      try {
        const [postRecord, commentRecords] = await Promise.all([
          forumApi.getPost(parsedId),
          forumApi.getPostComments(parsedId),
        ]);
        setPost(postRecord);
        setComments(commentRecords);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load post.");
      } finally {
        setLoading(false);
      }
    };

    void fetchPost();
  }, [postId]);

  const isOwner = currentUser?.id === post?.createdBy;

  const handleDelete = async () => {
    if (!post || !window.confirm("Delete this post and all its comments?")) {
      return;
    }

    try {
      setActionError(null);
      setDeleting(true);
      await forumApi.deletePost(post.id);
      navigate(`/companies/${post.companyId}`);
    } catch (err) {
      setActionError(
        err instanceof Error ? err.message : "Failed to delete post.",
      );
    } finally {
      setDeleting(false);
    }
  };

  const handleAddComment = async (event: React.FormEvent) => {
    event.preventDefault();

    if (!post || !currentUser || !newComment.trim()) {
      return;
    }

    setSubmitting(true);
    try {
      setActionError(null);
      const comment = await forumApi.createComment(post.id, {
        body: newComment.trim(),
      });
      setComments((current) => [...current, comment]);
      setNewComment("");
    } catch (err) {
      setActionError(
        err instanceof Error ? err.message : "Failed to post comment.",
      );
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <PageLayout title="Post" subtitle="Loading post details...">
        <p className="empty-state">Loading post...</p>
      </PageLayout>
    );
  }

  if (error || !post) {
    return (
      <PageLayout title="Post" subtitle="Discussion unavailable.">
        <Notice tone="error">{error || "Post not found."}</Notice>
      </PageLayout>
    );
  }

  return (
    <PageLayout
      title={post.title}
      subtitle={`Created by user ${post.createdBy} on ${new Date(post.createdAt).toLocaleString()}`}
      actions={
        <div className="action-row">
          <button
            className="button button--secondary"
            onClick={() => navigate(-1)}
          >
            Back
          </button>
          {isOwner ? (
            <>
              <button
                className="button button--ghost"
                disabled={deleting}
                onClick={() => navigate(`/posts/${post.id}/edit`)}
              >
                Edit
              </button>
              <button
                className="button button--danger"
                disabled={deleting}
                onClick={handleDelete}
              >
                {deleting ? "Deleting..." : "Delete"}
              </button>
            </>
          ) : null}
        </div>
      }
    >
      {actionError ? <Notice tone="error">{actionError}</Notice> : null}
      {!isAuthenticated ? (
        <Notice tone="info">Log in to comment on this post.</Notice>
      ) : null}
      {currentUser && !isOwner ? (
        <Notice tone="info">
          Only the post owner can edit or delete this post.
        </Notice>
      ) : null}
      <PostVoteControls
        post={post}
        onPostChange={(updatedPost) => setPost(updatedPost)}
      />
      <p className="content-body">{post.body}</p>

      <hr className="divider" />

      <div className="stack">
        <h2 className="section-title">Comments ({comments.length})</h2>
        {comments.length === 0 ? (
          <p className="empty-state">No comments yet.</p>
        ) : (
          <ul className="list">
            {comments.map((comment) => (
              <li key={comment.id} className="list-item">
                <p className="content-body">{comment.body}</p>
                <p className="meta">
                  By user {comment.createdBy} on{" "}
                  {new Date(comment.createdAt).toLocaleString()}
                </p>
              </li>
            ))}
          </ul>
        )}

        {isAuthenticated ? (
          <form className="form-grid" onSubmit={handleAddComment}>
            <div className="field">
              <label htmlFor="comment">Add a comment</label>
              <textarea
                id="comment"
                value={newComment}
                onChange={(event) => setNewComment(event.target.value)}
                rows={4}
                disabled={submitting}
              />
            </div>
            <button
              className="button button--primary"
              type="submit"
              disabled={submitting || !newComment.trim()}
            >
              {submitting ? "Posting..." : "Post Comment"}
            </button>
          </form>
        ) : null}
      </div>
    </PageLayout>
  );
};

export default PostDetailPage;

// frontend/src/pages/PostDetailPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import NoticeBanner from "../components/NoticeBanner.vue";
import PageLayout from "../components/PageLayout.vue";
import PostVoteControls from "../components/PostVoteControls.vue";
import { useAuth } from "../composables/useAuth";
import { forumApi } from "../services/api/forumApi";
import type { Comment, Post } from "../types";

const route = useRoute();
const router = useRouter();
const auth = useAuth();

const parsedPostId = computed(() => Number(route.params.postId));

const post = ref<Post | null>(null);
const comments = ref<Comment[]>([]);
const newComment = ref("");
const loading = ref(true);
const error = ref("");
const submitting = ref(false);
const deleting = ref(false);
const actionError = ref("");

const isOwner = computed(() => auth.state.currentUser?.id === post.value?.createdBy);

onMounted(async () => {
  if (!parsedPostId.value) {
    error.value = "Invalid post ID.";
    loading.value = false;
    return;
  }

  try {
    const [postRecord, commentRecords] = await Promise.all([
      forumApi.getPost(parsedPostId.value),
      forumApi.getPostComments(parsedPostId.value),
    ]);
    post.value = postRecord;
    comments.value = commentRecords;
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to load post.";
  } finally {
    loading.value = false;
  }
});

const handleDelete = async () => {
  if (!post.value || !window.confirm("Delete this post and all its comments?")) {
    return;
  }

  try {
    actionError.value = "";
    deleting.value = true;
    await forumApi.deletePost(post.value.id);
    await router.push(`/companies/${post.value.companyId}`);
  } catch (err) {
    actionError.value = err instanceof Error ? err.message : "Failed to delete post.";
  } finally {
    deleting.value = false;
  }
};

const handleAddComment = async () => {
  if (!post.value || !auth.state.currentUser || !newComment.value.trim()) {
    return;
  }

  submitting.value = true;

  try {
    actionError.value = "";
    const comment = await forumApi.createComment(post.value.id, {
      body: newComment.value.trim(),
    });
    comments.value = [...comments.value, comment];
    newComment.value = "";
  } catch (err) {
    actionError.value = err instanceof Error ? err.message : "Failed to post comment.";
  } finally {
    submitting.value = false;
  }
};

const updatePost = (updatedPost: Post) => {
  post.value = updatedPost;
};
</script>

<template>
  <PageLayout
    v-if="!loading && post"
    :title="post.title"
    :subtitle="`Created by user ${post.createdBy} on ${new Date(post.createdAt).toLocaleString()}`"
  >
    <template #actions>
      <div class="action-row">
        <button class="button button--secondary" @click="router.back()">Back</button>
        <button
          v-if="isOwner"
          class="button button--ghost"
          :disabled="deleting"
          @click="router.push(`/posts/${post.id}/edit`)"
        >
          Edit
        </button>
        <button
          v-if="isOwner"
          class="button button--danger"
          :disabled="deleting"
          @click="handleDelete"
        >
          {{ deleting ? "Deleting..." : "Delete" }}
        </button>
      </div>
    </template>

    <NoticeBanner v-if="actionError" tone="error">{{ actionError }}</NoticeBanner>
    <NoticeBanner v-if="!auth.isAuthenticated.value">
      Log in to comment on this post.
    </NoticeBanner>
    <NoticeBanner v-if="auth.state.currentUser && !isOwner">
      Only the post owner can edit or delete this post.
    </NoticeBanner>

    <PostVoteControls :post="post" @changed="updatePost" />
    <p class="content-body">{{ post.body }}</p>

    <hr class="divider" />

    <div class="stack">
      <h2 class="section-title">Comments ({{ comments.length }})</h2>

      <p v-if="comments.length === 0" class="empty-state">No comments yet.</p>
      <ul v-else class="list">
        <li v-for="comment in comments" :key="comment.id" class="list-item">
          <p class="content-body">{{ comment.body }}</p>
          <p class="meta">
            By user {{ comment.createdBy }} on {{ new Date(comment.createdAt).toLocaleString() }}
          </p>
        </li>
      </ul>

      <form v-if="auth.isAuthenticated.value" class="form-grid" @submit.prevent="handleAddComment">
        <div class="field">
          <label for="comment">Add a comment</label>
          <textarea id="comment" v-model="newComment" rows="4" :disabled="submitting" />
        </div>
        <button
          class="button button--primary"
          type="submit"
          :disabled="submitting || !newComment.trim()"
        >
          {{ submitting ? "Posting..." : "Post Comment" }}
        </button>
      </form>
    </div>
  </PageLayout>

  <PageLayout v-else-if="loading" title="Post" subtitle="Loading post details...">
    <p class="empty-state">Loading post...</p>
  </PageLayout>

  <PageLayout v-else title="Post" subtitle="Discussion unavailable.">
    <NoticeBanner tone="error">{{ error || "Post not found." }}</NoticeBanner>
  </PageLayout>
</template>
