// frontend/src/pages/SignupPage.vue
<script setup lang="ts">
import { ref } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";
import NoticeBanner from "../components/NoticeBanner.vue";
import PageLayout from "../components/PageLayout.vue";
import { useAuth } from "../composables/useAuth";

const auth = useAuth();
const router = useRouter();
const route = useRoute();

const username = ref("");
const password = ref("");
const loading = ref(false);
const error = ref("");

const handleSubmit = async () => {
  if (!username.value.trim()) {
    error.value = "Username is required.";
    return;
  }

  if (!password.value) {
    error.value = "Password is required.";
    return;
  }

  loading.value = true;
  error.value = "";

  try {
    await auth.signup(username.value.trim(), password.value);
    const redirectTo =
      typeof route.query.redirect === "string"
        ? route.query.redirect
        : "/companies";
    await router.replace(redirectTo);
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to sign up.";
  } finally {
    loading.value = false;
  }
};
</script>

<template>
  <PageLayout
    title="Create ArtHub Account"
    subtitle="Set up an account to create companies, posts, and comments."
    narrow
  >
    <NoticeBanner v-if="error" tone="error">
      {{ error }}
    </NoticeBanner>

    <form class="form-grid" @submit.prevent="handleSubmit">
      <div class="field">
        <label for="username">Username</label>
        <input
          id="username"
          v-model="username"
          type="text"
          :disabled="loading"
          autocomplete="username"
        />
      </div>

      <div class="field">
        <label for="password">Password</label>
        <input
          id="password"
          v-model="password"
          type="password"
          :disabled="loading"
          autocomplete="new-password"
        />
      </div>

      <button class="button button--primary button--full" type="submit" :disabled="loading">
        {{ loading ? "Creating account..." : "Sign Up" }}
      </button>
    </form>

    <p class="meta">
      Already have an account? <RouterLink to="/login">Log in</RouterLink>.
    </p>
  </PageLayout>
</template>

// frontend/src/pages/SignupPage.tsx
import React, { useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import Notice from "../components/Notice";
import PageLayout from "../components/PageLayout";
import { useAuth } from "../context/AuthContext";

type SignupLocationState = {
  from?: {
    pathname?: string;
  };
};

const SignupPage: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { isAuthenticated, isBootstrapping, signup } = useAuth();

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!isBootstrapping && isAuthenticated) {
      navigate("/companies", { replace: true });
    }
  }, [isAuthenticated, isBootstrapping, navigate]);

  if (isBootstrapping) {
    return (
      <PageLayout title="Create ArtHub Account" subtitle="Restoring your session..." narrow>
        <p className="empty-state">Loading session...</p>
      </PageLayout>
    );
  }

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();

    if (!username.trim()) {
      setError("Username is required.");
      return;
    }
    if (!password) {
      setError("Password is required.");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      await signup(username.trim(), password);
      const redirectTo = (location.state as SignupLocationState | null)?.from?.pathname || "/companies";
      navigate(redirectTo, { replace: true });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to sign up.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <PageLayout
      title="Create ArtHub Account"
      subtitle="Set up an account to create companies, posts, and comments."
      narrow
    >
      {error ? <Notice tone="error">{error}</Notice> : null}
      <form className="form-grid" onSubmit={handleSubmit}>
        <div className="field">
          <label htmlFor="username">Username</label>
          <input
            id="username"
            type="text"
            value={username}
            onChange={(event) => setUsername(event.target.value)}
            disabled={loading}
            autoComplete="username"
          />
        </div>

        <div className="field">
          <label htmlFor="password">Password</label>
          <input
            id="password"
            type="password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            disabled={loading}
            autoComplete="new-password"
          />
        </div>

        <button className="button button--primary button--full" type="submit" disabled={loading}>
          {loading ? "Creating account..." : "Sign Up"}
        </button>
      </form>

      <p className="meta">
        Already have an account? <Link to="/login">Log in</Link>.
      </p>
    </PageLayout>
  );
};

export default SignupPage;
